### ISSUE TITLE
[Translations] - Guide Contributing

### ISSUE THREAD

**Issue by mandaputtra** [vuejs-id/docs-next#22]
menterjemahkan direktori `src/guide/contributing`. Tolong jangan menterjemahkan semuanya dan membuat 1 PR berisi lebih dari 3 berkas. Akan lebih mudah di review jika PR berisi 1 - 3 berkas saja.

- [ ] [doc-style-guide](https://github.com/vuejs-id/docs-next/blob/master/src/guide/contributing/doc-style-guide.md)
- [ ] [translations](https://github.com/vuejs-id/docs-next/blob/master/src/guide/contributing/translations.md)
- [ ] [writing-guide](https://github.com/vuejs-id/docs-next/blob/master/src/guide/contributing/writing-guide.md)

**Comment by mufidu** [comment]
Saya mau menerjemahkan direktori ini. Tapi ada beberapa bagian yang menurut saya kurang relevan kalau ditranslate, misalnya rekomendasi penggunaan Grammarly yang hanya bisa dipakai untuk bahasa Inggris. Lebih baik disesuain (dihapus atau diganti alternatif yang sesuai) atau ditranslate gitu aja ya?

**Comment by mandaputtra** [comment]
@mufidu sekiranya dibaca kurang mengenakan dan malah membungungkan tidak usah di terjemahkan tidak apa apa. Cetak garis miring saja

**Comment by mufidu** [comment]
@mandaputtra Cetak garis miring kaya gimana ya mas maksudnya?

**Comment by mandaputtra** [comment]
@mufidu seperti _ini (italic)_

**Comment by mufidu** [comment]
@mandaputtra ok mas bisa diassign ke saya?

**Comment by mufidu** [comment]
@mandaputtra mas buat yang [writing-guide](https://github.com/vuejs-id/docs-next/blob/master/src/guide/contributing/writing-guide.md) kayanya bakal ada pengubahan ya, seperti yang disebut [di sini](https://github.com/vuejs-id/docs-next#tata-cara-berkontibusi). Apa sudah ada aturan khususnya? Atau ada rujukan buat aturan penerjemahan docs ke bahasa Indonesia dari sumber lain?

**Comment by mandaputtra** [comment]
@mufidu untuk sekarang belum sempat di translasikan di writing guide. Terjemahkan dulu saja nanti sambil saya review.
