### ISSUE TITLE
[Translations] - Support Vuejs

### ISSUE THREAD

**Issue by mandaputtra** [vuejs-id/docs-next#26]
menterjemahkan direktori `src/support-vuejs`. Tolong jangan menterjemahkan semuanya dan membuat 1 PR berisi lebih dari 3 berkas. Akan lebih mudah di review jika PR berisi 1 - 3 berkas saja.

- [x] [support-vuejs](https://github.com/vuejs-id/docs-next/tree/master/src/support-vuejs)

**Comment by RezaZR** [comment]
@mandaputtra saya akan menerjemahkan 1 dokumen di bawah ini:

- [ ] support-vuejs
